version: "3.3"
services:
  app_test:
    build: .
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    container_name: app_test
    ports:
      - "3000:3000"
    restart: always